---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: pankaj
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "pankaj5000/scientific-calculator"  # Specify the Docker image to pull
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
      
    - name: Running container
      shell: docker run -it -d --name calculator__app pankaj5000/scientific-calculator  # Run Docker container
